sudo: required
services:
    - docker

before_install:
    - docker build -t liadmm/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true liadmm/docker-react npm run test -- --coverage